broker = 10.0.42.71
broker_port = 1883
mqtt_version = 5
num_publishers = 10
num_subscribers = 1
qos_publisher = 1
qos_subscriber = 1
topic = exp/throughput
payload = 64
interval = 100000
num_messages = 1000000
exec_time = 30
ramp_up = 0
ramp_down = 0
subscriber_timeout = 10
log_level = INFO
